name: flutter_application_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.10.0
  shared_preferences: ^2.5.2
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  

# flutter:
#   uses-material-design: true
#   assets:
#     - images/meteoroid.png
#     - images/spaceship.png
